name: 'README Template'
author: 'Kasper Henningsen'
description: 'Insert variables into markdown file using a template file'
inputs:
  template:
    description: 'The file to use as template'
    required: true
    default: 'TEMPLATE.md'
  output:
    description: 'The output file'
    required: true
    default: 'README.md'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
